export class Diagnosis {
  finding_id:number;
  befund_id:number;
  aura_index:string;
  patient_id:number;
  age:number;
  examination_type:string;
  examination_date:Date;
  examination_number:number;
  diagnosis:string;
  diagnosis_clean:string;
  organ:string;
  organ_zuordnung:string;
  source:string;
  t:string;
  n:string;
  m:string;
  g:string;
  r:string;
  l:string;
  v:string;
}
